package com.amancay.entity;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import lombok.Getter;
import lombok.Setter;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "reviews")
@Getter
public class Review {

    private static final int MIN_RATING = 1;
    private static final int MAX_RATING = 5;
    private static final int MAX_TITLE_LENGTH = 150;

    // The id is assigned by the publish() factory, never generated by the database.
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    // Product and user are stored as plain identifiers so the module stays
    // decoupled from the Product and User aggregates.
    @Column(name = "product_id", nullable = false, updatable = false)
    private UUID productId;

    @Column(name = "user_id", nullable = false, updatable = false)
    private UUID userId;

    @JdbcTypeCode(SqlTypes.SMALLINT)
    @Column(nullable = false)
    private int rating;

    @Column(length = MAX_TITLE_LENGTH)
    private String title;

    @Setter
    @Column(name = "comment", columnDefinition = "TEXT")
    private String comment;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ReviewStatus status = ReviewStatus.PUBLISHED;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Required by Hibernate, which instantiates entities reflectively before populating their
     * fields. It is {@code protected} on purpose: outside this package the only way to obtain a
     * review is {@link #publish}, so a half-built instance cannot leak into the rest of the code.
     */
    protected Review() {
    }

    /**
     * Creates a review that is complete and valid from its very first line, in state
     * {@link ReviewStatus#PUBLISHED} and with a freshly assigned identifier.
     *
     * <p>This is the only entry point for creating a review. Previously the service allocated a
     * bare instance and filled it in with five consecutive setter calls: between the first and the
     * last one the object existed in an invalid state, and forgetting a call still compiled and
     * only failed later against a not-null constraint. Concentrating construction here makes that
     * whole class of mistake unrepresentable.
     *
     * <p>The range checks duplicate the Bean Validation annotations on the request DTO. That is
     * deliberate: the DTO guards the HTTP boundary, this guards the domain against any other
     * caller that never goes through a controller.
     *
     * @param productId product being reviewed, required
     * @param userId    author of the review, required
     * @param rating    score between 1 and 5 inclusive
     * @param title     optional heading, at most 150 characters
     * @param comment   optional free text
     * @throws NullPointerException     if {@code productId} or {@code userId} is null, which would
     *                                  be a programming error rather than bad user input
     * @throws IllegalArgumentException if the rating is out of range or the title is too long;
     *                                  {@code ApiExceptionHandler} maps this to HTTP 400
     */
    public static Review publish(UUID productId, UUID userId, int rating, String title, String comment) {
        Review review = new Review();
        review.id = UUID.randomUUID();
        review.productId = Objects.requireNonNull(productId, "productId is required");
        review.userId = Objects.requireNonNull(userId, "userId is required");
        review.status = ReviewStatus.PUBLISHED;
        review.setRating(rating);
        review.setTitle(title);
        review.comment = comment;
        return review;
    }

    /**
     * Applies the author's edit (REV-03). Kept as a single entry point so the rating and title
     * rules are enforced on updates exactly as they are on creation.
     */
    public void edit(int rating, String title, String comment) {
        setRating(rating);
        setTitle(title);
        this.comment = comment;
    }

    /**
     * Guards the 1..5 range on every write, not only at construction time.
     */
    public void setRating(int rating) {
        if (rating < MIN_RATING || rating > MAX_RATING) {
            throw new IllegalArgumentException(
                    "rating must be between " + MIN_RATING + " and " + MAX_RATING + ", but was " + rating);
        }
        this.rating = rating;
    }

    /**
     * Guards the column length, so an oversized title fails as a 400 instead of reaching the
     * database and coming back as a driver error.
     */
    public void setTitle(String title) {
        if (title != null && title.length() > MAX_TITLE_LENGTH) {
            throw new IllegalArgumentException(
                    "title must be at most " + MAX_TITLE_LENGTH + " characters, but was " + title.length());
        }
        this.title = title;
    }
}
